-- AlterTable
ALTER TABLE `visit` MODIFY `chief_complaint` VARCHAR(191) NULL,
    MODIFY `present_illness` VARCHAR(191) NULL,
    MODIFY `suicide` VARCHAR(191) NULL,
    MODIFY `family_hx` VARCHAR(191) NULL,
    MODIFY `past_psychiatric_hx` VARCHAR(191) NULL,
    MODIFY `past_medical_hx` VARCHAR(191) NULL,
    MODIFY `forensic_hx` VARCHAR(191) NULL,
    MODIFY `social_hx` VARCHAR(191) NULL,
    MODIFY `drug_hx` VARCHAR(191) NULL,
    MODIFY `substance` VARCHAR(191) NULL,
    MODIFY `personal_hx` VARCHAR(191) NULL,
    MODIFY `appearance` VARCHAR(191) NULL,
    MODIFY `behavior` VARCHAR(191) NULL,
    MODIFY `speech` VARCHAR(191) NULL,
    MODIFY `mood` VARCHAR(191) NULL,
    MODIFY `thought_form` VARCHAR(191) NULL,
    MODIFY `thought_content` VARCHAR(191) NULL,
    MODIFY `perception` VARCHAR(191) NULL,
    MODIFY `cognitive_state` VARCHAR(191) NULL,
    MODIFY `differential_diagnosis` VARCHAR(191) NULL,
    MODIFY `management` VARCHAR(191) NULL;
